sudo: false
language: php
php:
  - 7.4
  - 7.0
  - 5.6
  - 5.5

matrix:
  fast_finish: true

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
