# For details of what checks are run for PRs please refer below
# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: DEMO

# @TODO make this an integration test


on:
  push:
    branches: ["master", "next"]
    paths:
      - '.github/workflows/demo.yml'
      - 'src/**'
      - 'demo/**'
      - 'composer.*'
  pull_request:
    paths:
      - '.github/workflows/demo.yml'
      - 'src/**'
      - 'demo/**'
      - 'composer.*'
  workflow_dispatch:
  schedule:
    # schedule weekly tests, since dependencies are not intended to be locked
    # this means: at 23:42 on Fridays
    - cron: '42 23 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PHP_VERSION_LATEST: "8.2"
  PHP_PROJECT_EXT: dom,filter,json,libxml # via `composer info -pt` and removed dev req
  REPORTS_DIR: CI_reports
  DEMO_TOOL_PATH: demo/.tool
  CDX_CP_TOOLS_VERSION_OVERRIDE: in-dev
  CDX_CP_TOOLS_EXCLUDE_LIBS: 1
  CDX_CP_TOOLS_EXCLUDE_COMPOSER: 1

jobs:
  reproducible:
    name: >
      R: "${{ matrix.subject }}"
      (${{ matrix.spec-version }}
      ${{ matrix.output-format }},
      c${{ matrix.composer }}
      p${{ matrix.php }},
      i:${{ matrix.install }}
      stdout:${{ matrix.stdout }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      REPORTS_ARTIFACT: demo-reproducible
    strategy:
      fail-fast: false
      matrix:
        subject: # list of reproducible demos
          - devReq
          - laravel-7.12.0
          - local
        php:
          - "8.2"  # latest
          - "8.1"  # lowest supported
        composer:
          - "v2"   # latest 2.x
          - "2.3"  # latest 2.3 = lowest supported
        output-format:
          # lowercase the format, since it is also used as a file extension when searching the original file
          - xml
          - json
        spec-version:
          - "1.4"
          - "1.3"
          - "1.2"
          - "1.1"
          # - "1.0" # not implemented
        stdout: [ false ]
        install: [ true , false ]
        exclude:
          # exclude unsupported combinations: json is defined in spec >= 1.2
          - output-format: json
            spec-version: "1.0"
          - output-format: json
            spec-version: "1.1"
        include:
          - # test with the lowest combination
            php: "8.1"          # lowest
            composer: "2.3"     # lowest
            # any other props
            spec-version: "1.4"
            subject: laravel-7.12.0
            output-format: xml
            stdout: false
          - # test if STDOUT receives no data except the SBOM
            stdout: true  # << the subject of this test-case
            php: "8.2"           # latest
            composer: "v2"       # latest
            spec-version: "1.4"  # latest
            # any other props
            subject: laravel-7.12.0
            output-format: xml
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Setup paths and folders
        run: |
          PWD="$(pwd -P)"
          OUT_FILE='${{ matrix.subject }}_php${{ matrix.php }}_composer${{ matrix.composer }}_bom.${{ matrix.spec-version }}.${{ matrix.output-format }}'
          COMPARE_FILE='bom.${{ matrix.spec-version }}.${{ matrix.output-format }}'
          DEMO_SUBJECT_DIR="$PWD"'/demo/${{ matrix.subject }}'
          echo "DEMO_PROJECT_DIR=$DEMO_SUBJECT_DIR/project" >> $GITHUB_ENV
          REPORTS_DIR_PATH="$PWD/$REPORTS_DIR"
          mkdir -p "$REPORTS_DIR_PATH"/'${{ matrix.subject }}'
          echo "REPORTS_DIR_PATH=$REPORTS_DIR_PATH" >> $GITHUB_ENV
          echo "OUT_FILE_PATH=$REPORTS_DIR_PATH/$OUT_FILE" >> $GITHUB_ENV
          echo "COMPARE_FILE_PATH=$DEMO_SUBJECT_DIR/results/$COMPARE_FILE" >> $GITHUB_ENV
      - name: Setup OMIT "dev"
        run: |
          OMIT_RULES=''
          if [ '${{ matrix.subject}}' != 'devReq' ]; then
            OMIT_RULES="$OMIT_RULES --omit=dev"
          fi
          echo "OMIT_RULES=$OMIT_RULES" >> $GITHUB_ENV
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:${{ matrix.composer }}
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        working-directory: ${{ env.DEMO_PROJECT_DIR }}
        shell: bash
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        if: ${{ steps.composer-cache.outputs.dir }}
        # see https://github.com/actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ github.job }}-${{ matrix.subject }}-php${{ matrix.php }}-${{ hashFiles('composer.*', 'demo/*/project/composer.*') }}
          restore-keys: |
            composer-${{ github.job }}-${{ matrix.subject }}-php${{ matrix.php }}-
            composer-${{ github.job }}-${{ matrix.subject }}-
      - name: Install composer plugin
        working-directory: ${{ env.DEMO_TOOL_PATH }}
        run: composer install
      - name: Install project dependencies & kick lockfile
        if: ${{ matrix.install }}
        working-directory: ${{ env.DEMO_PROJECT_DIR }}
        run: |
          composer setup
          rm composer.lock
      - name: Make SBOM to file
        if: ${{ ! matrix.stdout }}
        working-directory: ${{ env.DEMO_TOOL_PATH }}
        run: >
          composer CycloneDX:make-sbom
          -vvv
          $OMIT_RULES
          --validate
          --spec-version=${{ matrix.spec-version }}
          --output-reproducible
          --output-format=${{ matrix.output-format }}
          --output-file="$OUT_FILE_PATH"
          --
          ${{ env.DEMO_PROJECT_DIR }}/composer.json
      - name: Make SBOM to STDOUT
        if: ${{ matrix.stdout }}
        working-directory: ${{ env.DEMO_TOOL_PATH }}
        run: >
          composer CycloneDX:make-sbom
          -vvv
          $OMIT_RULES
          --validate
          --spec-version=${{ matrix.spec-version }}
          --output-reproducible
          --output-format=${{ matrix.output-format }}
          --output-file=-
          --
          ${{ env.DEMO_PROJECT_DIR }}/composer.json
          > "$OUT_FILE_PATH"
      - name: Compare reproducible SBOM
        run: >
          diff -s
          "$COMPARE_FILE_PATH"
          "$OUT_FILE_PATH"
      - name: Artifact reports
        if: ${{ failure() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPORTS_ARTIFACT }}-failed
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error
