# For details of what checks are run for PRs please refer below
name: PHP CI

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ["7.3", "7.4", "8.0"]
        composer-version: [1, 2]
    timeout-minutes: 30

    name: ${{ matrix.os}} php${{ matrix.php-versions }} omposer${{ matrix.php-versions }}
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v${{ matrix.composer-versions }}
          # extensions: json
          # coverage: pcov

      - name: Validate composer.json and composer.lock
        run: >
          composer validate
          --no-interaction
          --with-dependencies

      - name: Install dependencies
        run: >
          composer install
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist

      - name: Run test suite
        run: composer test

      - name: Run demo
        run: composer demo
