# For details of what checks are run for PRs please refer below
name: PHP CI

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ["7.1", "7.2", "7.3", "7.4", "8.0"]
    timeout-minutes: 30

    name: PHP ${{ matrix.os}} ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: dom # Required by phpunit
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer test
