# For details of what checks are run for PRs please refer below
# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: PHP CI

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:
  schedule:
    # schedule weekly tests, since dependencies are not intended to be pinned
    # this means: at 23:42 on Fridays
    - cron: '42 23 * * 5'

env:
  PHP_PROJECT_EXT: dom,json,xmlwriter
  REPORTS_DIR: CI_reports

jobs:
  tests:
    name: Tests (${{ matrix.os}}, ${{ matrix.php }}, ${{ matrix.dependencies }})
    runs-on: ${{ matrix.os }}
    env:
      REPORTS_ARTIFACT: tests-reports
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        php:
          - "8.0" # highest supported
          - "7.4"
          - "7.3" # lowest supported
        dependencies: [ "lowest", "highest" ]
        include:
          - # windows cutting edge highest
            os: windows-latest
            php: "8.0"
            dependencies: "highest"
          - # macos cutting edge highest
            os: macos-latest
            php: "8.0"
            dependencies: "highest"
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: dir setup
        run: mkdir ${{ env.REPORTS_DIR }}
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: pcov,xdebug
      - name: Determine composer cache directory on Linux/macOS
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: echo "COMPOSER_CACHE_DIR_PATH=$(composer config cache-dir)" >> $GITHUB_ENV
      - name: Determine composer cache directory on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: ECHO "COMPOSER_CACHE_DIR_PATH=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Cache dependencies installed with composer
        # see https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR_PATH }}
          key:          php${{ matrix.php }}-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: php${{ matrix.php }}-${{ matrix.dependencies }}-
      - name: Validate composer.json and composer.lock
        run: >
          composer validate
          --no-interaction
      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-dist --no-interaction --no-progress --prefer-lowest
      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Run PHPUnit tests
        run: >
          php
          -d zend.assertions=1
          -d assert.exception=1
          -d display_errors=On
          -d error_reporting=-1
          -d log_errors_max_len=0
          -d memory_limit=-1
          vendor/phpunit/phpunit/phpunit
          --log-junit=${{ env.REPORTS_DIR }}/tests.${{ matrix.os }}_php${{ matrix.php }}_${{ matrix.dependencies }}.junit.xml
          --coverage-clover=${{ env.REPORTS_DIR }}/coverage.${{ matrix.os}}_php${{ matrix.php }}_${{ matrix.dependencies }}.clover.xml
      - name: Artifact reports
        if: ${{ ! cancelled() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORTS_ARTIFACT }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error
  code-checker:
    name: Code analysis (${{ matrix.php }}, ${{ matrix.dependencies }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REPORTS_ARTIFACT: types-reports
    strategy:
      fail-fast: false
      matrix:
        include:
          - # highest supported
            php: "8.0"
            dependencies: "highest"
          - # lowest supported
            php: "7.3"
            dependencies: "lowest"
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR_PATH=$(composer config cache-dir)" >> $GITHUB_ENV
      - name: Cache dependencies installed with composer
        # see https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR_PATH }}
          key:          php${{ matrix.php }}-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: php${{ matrix.php }}-${{ matrix.dependencies }}-
      - name: Install psalm
        run: composer update --prefer-dist --no-interaction --no-progress
        working-directory: tools/psalm
      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-dist --no-interaction --no-progress --prefer-lowest
      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Run Psalm tests
        run: >
          php tools/psalm/vendor/vimeo/psalm/psalm
          --no-diff
          --no-cache
          --long-progress
          --report=${{ env.REPORTS_DIR }}/psalm.php${{ matrix.php }}_${{ matrix.dependencies }}.junit.xml
      - name: Artifact reports
        if: ${{ ! cancelled() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORTS_ARTIFACT }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error
  composer-unused:
    name: ComposerUnused
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR_PATH=$(composer config cache-dir)" >> $GITHUB_ENV
      - name: Cache dependencies installed with composer
        # see https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR_PATH }}
          key:          php8.0-highest-${{ hashFiles('**/composer.json') }}
          restore-keys: php8.0-highest-
      - name: Install composer-unused
        run: composer update --prefer-dist --no-interaction --no-progress
        working-directory: tools/composer-unused
      - name: Run composer-unused tests
        run: >
          php tools/composer-unused/vendor/icanhazstring/composer-unused/bin/composer-unused
          --no-progress
          --no-interaction
          --excludeDir=tools
  composer-require-checker:
    name: ComposerRequireChecker
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR_PATH=$(composer config cache-dir)" >> $GITHUB_ENV
      - name: Cache dependencies installed with composer
        # see https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR_PATH }}
          key:          php8.0-highest-${{ hashFiles('**/composer.json') }}
          restore-keys: php8.0-highest-
      - name: Install composer-require-checker
        run: composer update --prefer-dist --no-interaction --no-progress
        working-directory: tools/composer-require-checker
      - name: Install dependencies
        run: composer update --no-dev --prefer-dist --no-interaction --no-progress
      - name: Run composer-require-checker tests
        run: >
          php tools/composer-require-checker/vendor/maglnet/composer-require-checker/bin/composer-require-checker
          --no-interaction
          || :  # this report is optional
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR_PATH=$(composer config cache-dir)" >> $GITHUB_ENV
      - name: Cache dependencies installed with composer
        # see https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR_PATH }}
          key:          php8.0-highest-${{ hashFiles('**/composer.json') }}
          restore-keys: php8.0-highest-
      - name: Install PHP-CS-Fixer
        run: composer update --prefer-dist --no-interaction --no-progress
        working-directory: tools/php-cs-fixer
      - name: Run PHP-CS-Fixer tests
        run: >
          php tools/php-cs-fixer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer
          fix
          --dry-run
          --diff
          --using-cache=no
          --show-progress=dots
          --no-interaction
  demo:
    # test spec-versions 1.0 - 1.3
    name: Demo "${{ matrix.subject }}" (${{ matrix.php }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REPORTS_ARTIFACT: demo-output
    strategy:
      fail-fast: false
      matrix:
        include:
          - subject: symfony
            deps-pinned: false
            # highest supported by the project
            php: "8.0"
          - subject: symfony
            deps-pinned: false
            # lowest supported by the project
            php: "7.3"
          - subject: laravel-7.12.0
            deps-pinned: true
            # highest supported by this demo
            php: "7.4"
            reproducible: # relative paths to reproducible SBOM files
              xml: results/bom.xml
              json: results/bom.json
          - subject: laravel-7.12.0
            deps-pinned: true
            # lowest supported by the project
            php: "7.3"
            reproducible: # relative paths to reproducible SBOM files
              xml: results/bom.xml
              json: results/bom.json
          - subject: local
            deps-pinned: false
            # highest supported by the project
            php: "8.0"
          - subject: local
            deps-pinned: false
            # lowest supported by the project
            php: "7.3"
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup paths and folders
        run: |
          REPORTS_DIR_PATH="$(pwd -P)/$REPORTS_DIR/${{ matrix.subject }}"
          mkdir -p "$REPORTS_DIR_PATH"
          echo "REPORTS_DIR_PATH=$REPORTS_DIR_PATH" >> $GITHUB_ENV
          echo "OUT_FILE_HELP_PATH=$REPORTS_DIR_PATH/help.php${{ matrix.php }}.txt" >> $GITHUB_ENV
          echo "OUT_FILE_XML_PATH=$REPORTS_DIR_PATH/bom.php${{ matrix.php }}.xml" >> $GITHUB_ENV
          echo "OUT_FILE_JSON_PATH=$REPORTS_DIR_PATH/bom.php${{ matrix.php }}.json" >> $GITHUB_ENV
      - name: Set DEMO_RUN_DIR_PATH
        run : echo "DEMO_RUN_DIR_PATH=$(pwd -P)" >> $GITHUB_ENV
        working-directory: demo/${{ matrix.subject }}/project
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR_PATH=$(composer config cache-dir)" >> $GITHUB_ENV
      - name: Cache dependencies installed with composer
        # see https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR_PATH }}
          key:          php${{ matrix.php }}-highest-${{ hashFiles('**/composer.json') }}
          restore-keys: php${{ matrix.php }}-highest-
      - name: Install dependencies (non-pinned)
        if: ${{ ! matrix.deps-pinned }}
        run: composer update --prefer-dist --no-interaction --no-progress
        working-directory: ${{ env.DEMO_RUN_DIR_PATH }}
      - name: Install dependencies (pinned)
        if: ${{ matrix.deps-pinned }}
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: ${{ env.DEMO_RUN_DIR_PATH }}
      - name: Show help
        run: >
          composer make-bom
          --help
          > "$OUT_FILE_HELP_PATH"
        working-directory: ${{ env.DEMO_RUN_DIR_PATH }}
      - name: Make XML SBOM
        run: >
          composer make-bom
          -vvv
          --exclude-dev
          --output-file="$OUT_FILE_XML_PATH"
          --output-format=XML
          --spec-version=1.1
        working-directory: ${{ env.DEMO_RUN_DIR_PATH }}
      - name: Make JSON SBOM
        run: >
          composer make-bom
          -vvv
          --exclude-dev
          --output-file="$OUT_FILE_JSON_PATH"
          --output-format=JSON
          --spec-version=1.2
        working-directory: ${{ env.DEMO_RUN_DIR_PATH }}
      - name: Artifact reports
        if: ${{ ! cancelled() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORTS_ARTIFACT }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error
      - name: Compare reproducible XML SBOM
        if: ${{ matrix.reproducible.xml }}
        run: >
          diff
          ${{ matrix.reproducible.xml }}
          "$OUT_FILE_XML_PATH"
        working-directory: demo/${{ matrix.subject }}
      - name: Compare reproducible JSON SBOM
        if: ${{ matrix.reproducible.json }}
        run: >
          diff
          ${{ matrix.reproducible.json }}
          "$OUT_FILE_JSON_PATH"
        working-directory: demo/${{ matrix.subject }}
