# For details of what checks are run for PRs please refer below
name: PHP CI

on:
  push:
    # TODO remove my custom branch
    branches: ["master", "php_ge_73"]
  pull_request:
  workflow_dispatch:
  schedule:
    # schedule weekly tests, since install dependencies are not intended to be pinned
    # this means: at 23:42 on Fridays
    - cron: '42 23 * * 5'

jobs:
  tests:
    name: >
      ${{ matrix.os}}
      php${{ matrix.php }}
      ${{ matrix.stability }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: ["7.3", "7.4", "8.0"]
        stability: [prefer-lowest, prefer-stable]
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          tools: composer:v2
          coverage: none
      - name: Validate composer.json and composer.lock
        run: >
          composer validate
          --no-interaction
          --with-dependencies
      - name: Install dependencies
        run: >
          composer update
          --${{ matrix.stability }}
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist
      - name: Install tool for static code analysis
        run: >
          composer -dtools/phpstan install
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist
      - name: Run static code analysis
        run: composer run-script test:sca
      - name: Run phpunit tests
        run: composer run-script test:unit
  style:
    name: Coding Standards
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: json
          tools: composer:v2
          coverage: none
      - name: Install tool
        run: >
          composer -dtools/php-cs-fixer install
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist
      - name: Test coding standards
        run: composer run-script test:cs
