# For details of what checks are run for PRs please refer below
name: PHP CI

on:
  push:
    # TODO remove my custom branch
    branches: ["master", "php_ge_73"]
  pull_request:
  workflow_dispatch:
  schedule:
    # schedule weekly tests, since dependencies are not intended to be pinned
    # this means: at 23:42 on Fridays
    - cron: '42 23 * * 5'

jobs:
  tests:
    name: Tests (${{ matrix.os}}, ${{ matrix.php }}, ${{ matrix.stability }})
    runs-on: ${{ matrix.os }}
    env:
      REPORTS_DIR: reports
      REPORTS_ARTIFACT: test-reports
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        php:
          - "7.3"
          - "7.4"
          - "8.0"
        stability:
          - lowest
          - stable
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # @TODO add all required extensions for plugin and tools
          extensions: json
          coverage: pcov
      - name: Validate composer.json and composer.lock
        run: >
          php
          ./tools/composer validate
          --with-dependencies
          --no-interaction
      - name: Install dependencies
        run: >
          php
          ./tools/composer update
          --prefer-${{ matrix.stability }}
          --prefer-dist
          --no-interaction
          --no-progress
          --no-suggest
      - name: Install tool for static code analysis
        run: >
          php
          ./tools/composer -dtools/phpstan install
          --prefer-dist
          --no-interaction
          --no-progress
          --no-suggest
      - name: Run static code analysis
        run: >
          php
          tools/phpstan/bin/phpstan.phar analyse
          --verbose
          --no-progress
          --no-interaction
      - name: Run phpunit tests
        run: >
          php ./tools/composer exec --
          phpunit
          --log-junit=${REPORTS_DIR}/tests.${{ matrix.os }}_php${{ matrix.php }}_${{ matrix.stability }}.junit.xml
          --coverage-clover=${REPORTS_DIR}/coverage.${{ matrix.os}}_php${{ matrix.php }}_${{ matrix.stability }}.clover.xml
          --no-interaction
          --do-not-cache-result
      - name: Artifact reports
        if: ${{ ! cancelled() && ! matrix.no-reports }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORTS_ARTIFACT }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error
  style:
    name: Coding Standards
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          # @TODO add all required extensions for plugin and tools
          extensions: json
          coverage: none
      - name: Test coding standards
        run: >
          php
          tools/php-cs-fixer
          fix --dry-run
          --diff-format=udiff
          --using-cache=no
          --show-progress=dots
          --no-interaction
  demo:
    name: Demo (composer${{ matrix.composer }})
    needs: [ 'tests' ]
    runs-on: ubuntu-latest
    env:
      PLUGIN_DIR: plugin
      DEMO_DIR: demo
      REPORTS_DIR: reports
      REPORTS_ARTIFACT: demo-reports
    strategy:
      fail-fast: false
      matrix:
        composer:
          - 1
          - 2
    timeout-minutes: 5
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.PLUGIN_DIR }}
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          # @TODO add all required extensions for plugin and tools
          tools: composer:v${{ matrix.compser }}
          coverage: none
      - name: Setup Demo
        run: |
          set -ex

          mkdir -p ${REPORTS_DIR}
          mkdir -p ${DEMO_DIR}

          php -f ${PLUGIN_DIR}/tests/plugin/setup.php -- ${DEMO_DIR}

          composer \
            -d${DEMO_DIR} \
            install \
              --prefer-dist \
              --no-interaction \
              --no-progress \
              --no-suggest
      - name: Demo Help
        run: >
          composer -d${DEMO_DIR}
          make-bom -h
          > ${REPORTS_DIR}/help.txt
      - name: Demo XML
        run: >
          composer -d${DEMO_DIR}
          make-bom
          --output-file=-
          > ${REPORTS_DIR}/bom.xml
      - name: Demo JSON
        run: >
          composer -d${DEMO_DIR}
          make-bom --json
          --output-file=-
          > ${REPORTS_DIR}/bom.json
      - name: Artifact reports
        if: ${{ ! cancelled() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORTS_ARTIFACT }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error



