# For details of what checks are run for PRs please refer below
# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: PHP CI

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:
  schedule:
    # schedule weekly tests, since dependencies are not intended to be pinned
    # this means: at 23:42 on Fridays
    - cron: '42 23 * * 5'

env:
  PHP_VERSION_LATEST: "8.2"
  PHP_PROJECT_EXT: dom,filter,json,libxml,simplexml  # via `composer info -pt`
  REPORTS_DIR: CI_reports

jobs:
  tests:
    name: Tests (${{ matrix.os}}, ${{ matrix.php }}, ${{ matrix.dependencies }})
    runs-on: ${{ matrix.os }}
    env:
      REPORTS_ARTIFACT: tests-reports
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        php:
          - "8.2" # highest supported
          - "8.1"
          - "8.0"
          - "7.4"
          - "7.3" # lowest supported
        dependencies: [ "lowest", "highest" ]
        exclude:
          - # unstable combinations: throws PHP Deprecated warnings
            php: "8.2"
            dependencies: "lowest"
          - # unstable combinations: throws PHP Deprecated warnings
            php: "8.1"
            dependencies: "lowest"
        include:
          - # Windows highest
            os: windows-latest
            php: "8.2"
            dependencies: "highest"
          - # MacOS highest
            os: macos-latest
            php: "8.2"
            dependencies: "highest"
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: dir setup
        run: mkdir ${{ env.REPORTS_DIR }}
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: pcov,xdebug
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        # see https://github.com/actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ github.job }}-${{ runner.os }}-${{ matrix.php }}-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ github.job }}-${{ runner.os }}-${{ matrix.php }}-${{ matrix.dependencies }}-
            composer-${{ github.job }}-${{ runner.os }}-${{ matrix.php }}-
            composer-${{ github.job }}-${{ runner.os }}-
      - name: Validate composer.json and composer.lock
        run: >
          composer validate
          --no-interaction
      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: |
          composer remove --dev 'roave/security-advisories'
          composer update --prefer-dist --no-interaction --no-progress --prefer-lowest
      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Run PHPUnit tests
        run: >
          php
          -d zend.assertions=1
          -d assert.exception=1
          -d display_errors=On
          -d error_reporting=-1
          -d log_errors_max_len=0
          -d memory_limit=-1
          vendor/phpunit/phpunit/phpunit
          --log-junit=${{ env.REPORTS_DIR }}/tests.${{ matrix.os }}_php${{ matrix.php }}_${{ matrix.dependencies }}.junit.xml
          --coverage-clover=${{ env.REPORTS_DIR }}/coverage.${{ matrix.os}}_php${{ matrix.php }}_${{ matrix.dependencies }}.clover.xml
      - name: Artifact reports
        if: ${{ ! cancelled() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPORTS_ARTIFACT }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error
  code-checker:
    name: Code analysis (${{ matrix.php }}, ${{ matrix.dependencies }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REPORTS_ARTIFACT: types-reports
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.2"  # highest supported
          - "8.1"
          - "8.0"
          - "7.4"
        dependencies: [ "highest" ]
        include:
          - # lowest supported
            php: "7.3"
            dependencies: "lowest"
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        # see https://github.com/actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ github.job }}-${{ runner.os }}-${{ matrix.php }}-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ github.job }}-${{ runner.os }}-${{ matrix.php }}-${{ matrix.dependencies }}-
            composer-${{ github.job }}-${{ runner.os }}-${{ matrix.php }}-
            composer-${{ github.job }}-${{ runner.os }}-
      - name: Install psalm
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: tools/psalm
      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: |
          composer remove --dev 'roave/security-advisories'
          composer update --prefer-dist --no-interaction --no-progress --prefer-lowest
      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Run Psalm tests
        run: >
          php tools/psalm/vendor/vimeo/psalm/psalm
          --no-diff
          --no-cache
          --long-progress
          --php-version='${{ matrix.php }}'
          --report='${{ env.REPORTS_DIR }}/psalm.php${{ matrix.php }}_${{ matrix.dependencies }}.junit.xml'
      - name: Artifact reports
        if: ${{ ! cancelled() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPORTS_ARTIFACT }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error
  composer-unused:
    name: ComposerUnused
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION_LATEST }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        # see https://github.com/actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ github.job }}-${{ runner.os }}-
      - name: Install composer-unused
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: tools/composer-unused
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress
      - name: Run composer-unused tests
        run: >
          php tools/composer-unused/vendor/icanhazstring/composer-unused/bin/composer-unused
          --no-progress
          --no-interaction
          --excludeDir=tools
  composer-require-checker:
    name: ComposerRequireChecker
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION_LATEST }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        # see https://github.com/actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ github.job }}-${{ runner.os }}-
      - name: Install composer-require-checker
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: tools/composer-require-checker
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress
      - name: Run composer-require-checker tests
        run: >
          php tools/composer-require-checker/vendor/maglnet/composer-require-checker/bin/composer-require-checker
          --no-interaction
          || :  # this report is optional
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" ## php82 not supported yet ${{ env.PHP_VERSION_LATEST }}
          extensions: ${{ env.PHP_PROJECT_EXT }}
          tools: composer:v2
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        # see https://github.com/actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ github.job }}-${{ runner.os }}-
      - name: Install PHP-CS-Fixer
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: tools/php-cs-fixer
      - name: Run PHP-CS-Fixer tests
        run: >
          php tools/php-cs-fixer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer
          fix
          --dry-run
          --diff
          --using-cache=no
          --show-progress=dots
          --no-interaction
  composer-normalize:
    name: Composer normalize
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION_LATEST }}
          tools: composer:v2
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        # see https://github.com/actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ github.job }}-${{ runner.os }}-
      - name: Install composer-normalize
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: tools/composer-normalize
      - name: Run composer-normalize tests
        run: >
          composer -dtools/composer-normalize
          normalize
          --dry-run
          --diff
          --no-check-lock
          --no-update-lock
          --no-interaction
          $PWD/composer.json
