# For details of what checks are run for PRs please refer below
name: PHP CI

on:
  push:
    # TODO remove my custom branch
    branches: ["master", "php_ge_73"]
  pull_request:
  workflow_dispatch:
  schedule:
    # schedule weekly tests, since dependencies are not intended to be pinned
    # this means: at 23:42 on Fridays
    - cron: '42 23 * * 5'

env:
  reports-directory: .CItmp
  reports-artifact: reports

jobs:
  tests:
    name: Tests (${{ matrix.os}}, ${{ matrix.php }}, ${{ matrix.stability }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        php:
          - "7.3"
          - "7.4"
          - "8.0"
        stability:
          - lowest
          - stable
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: pcov
      - name: Validate composer.json and composer.lock
        run: >
          php
          ./tools/composer validate
          --with-dependencies
          --no-interaction
      - name: Install dependencies
        run: >
          php
          ./tools/composer update
          --prefer-${{ matrix.stability }}
          --prefer-dist
          --no-interaction
          --no-progress
          --no-suggest
      - name: Install tool for static code analysis
        run: >
          php
          ./tools/composer -dtools/phpstan install
          --prefer-dist
          --no-interaction
          --no-progress
          --no-suggest
      - name: Run static code analysis
        run: >
          php
          tools/phpstan/bin/phpstan.phar analyse
          --verbose
          --no-progress
          --no-interaction
      - name: Run phpunit tests
        run: >
          php ./tools/composer exec --
          phpunit
          --log-junit=${{ env.reports-directory }}/tests.${{ matrix.os}}_php${{ matrix.php }}_${{ matrix.stability }}.junit.xml
          --coverage-clover=${{ env.reports-directory }}/coverage.${{ matrix.os}}_php${{ matrix.php }}_${{ matrix.stability }}.clover.xml
          --no-interaction
          --do-not-cache-result
      - name: Artifact reports
        if: ${{ ! cancelled() && ! matrix.no-reports }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.reports-artifact }}
          path: ${{ env.reports-directory }}
          if-no-files-found: error
  style:
    name: Coding Standards
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: json
          coverage: none
      - name: Test coding standards
        run: >
          php
          tools/php-cs-fixer
          fix --dry-run
          --diff-format=udiff
          --using-cache=no
          --show-progress=dots
          --no-interaction
